// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtWM-mnAQOGFDNf6qFjfNvyGNrLZvtRc4',
    appId: '1:477806703415:android:76aef3b76db29be4c820b2',
    messagingSenderId: '477806703415',
    projectId: 'inkwell-fbee9',
    storageBucket: 'inkwell-fbee9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFl1H8BYtzEZBqtH0WhnIEyPGwQY2vIvU',
    appId: '1:477806703415:ios:88c77f9954d25a26c820b2',
    messagingSenderId: '477806703415',
    projectId: 'inkwell-fbee9',
    storageBucket: 'inkwell-fbee9.appspot.com',
    iosBundleId: 'com.example.inkwell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFl1H8BYtzEZBqtH0WhnIEyPGwQY2vIvU',
    appId: '1:477806703415:ios:88c77f9954d25a26c820b2',
    messagingSenderId: '477806703415',
    projectId: 'inkwell-fbee9',
    storageBucket: 'inkwell-fbee9.appspot.com',
    iosBundleId: 'com.example.inkwell',
  );
}
